plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bypass.pinbypass'
    compileSdk 34
    defaultConfig {
        applicationId "com.bypass.pinbypass"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    compileOnly 'com.github.libxposed:api:100.2.1'
}

repositories {
    maven { url 'https://jitpack.io' }
}